### ISSUE TITLE
error in using etterguillaume/MiniscopeAnalysis

### ISSUE THREAD

**Issue by xiaoyup** [etterguillaume/MiniscopeAnalysis#1]
I followed the the instructions, put all folders name in the msBatchFileList.m, then run msBatchRun2018.   Got errors:

Undefined function 'hour' for input arguments of type 'double'.

Error in msBatchRun2018 (line 54)
    analysis_time =strcat(date,'_', num2str(hour(now)),'-',num2str(minute(now)),'-',num2str(floor(second(now))));

**Comment by hahnjohannes** [comment]
The functions hour, minute, second are in the financial toolbox. 
I used these two lines to replace it:  
analysis_time = strrep(char(datetime),':','-');
analysis_time = strrep(analysis_time,' ','_');
